spring.application.name=EventManagerApp
spring.liquibase.enabled=false
#Config server SQL server
spring.datasource.url=${DB_SOURCE:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1}
spring.datasource.username=apiuser
spring.datasource.password=${DB_PASSWORD:1234}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql=TRACE
#Config server MongoDB
spring.data.mongodb.uri=${MONGO_DB_SOURCE}
#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
#logging.level.org.mongodb.driver=DEBUG
#Servlet config
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
#JWT
jwt.secret=${JWT_SECRET:LLAVESECRETADEFAULTXD}
#expiration time for access token 15 minutes
jwt.expiration.access=900000
#expiration time for refresh token (20 days)
jwt.expiration.refresh=1728000000
#Server config
server.port=8080
server.servlet.context-path=/api
QRPATH=${QR_CODE_PATH}
EVENTS_PICTURES=${EVENTS_PICTURES}
##Email service
#api.email.key=${KEY_EMAIL_API:202033}
#api.corp.email=${CORP_EMAIL:example@gmail.com}
spring.output.ansi.enabled=always