#Config server SQL server
spring.datasource.url=${DB_SOURCE:jdbc:mysql://localhost:3306/dbtony}
spring.datasource.username=apiuser
spring.datasource.password=${DB_PASSWORD:1234}
spring.application.name=app
spring.jpa.hibernate.ddl-auto=create-drop
#Config server MongoDB

#Servlet config
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#JWT
jwt.secret=${JWT_SECRET:LLAVESECRETADEFAULTXD}
#expiration time for access token (1 hour)
jwt.expiration=3600000
#expiration time for refresh token (20 days)
jwt.expiration.refresh=1728000000

#Server config
server.port=8080
server.servlet.context-path=/api
QRPATH=${QR_CODE_PATH:/}
IMAGEPATH=${IMAGE_PATH:/}

#Email service
api.email.key=${KEY_EMAIL_API:202033}
api.corp.email=${CORP_EMAIL:example@gmail.com}